### ISSUE TITLE
Oct 2022 : CCC SRMIST KTR : CPS 02 : Sprint II Coding

### ISSUE THREAD

**Issue by dharsan19** [VikashPR/CCC-Hackerrank#1]
P 502 - Tisha and Orange Sorting --> Python3 compile Time Error

**Comment by VikashPR** [comment]
@dharsan19 thank you for rising issue
can you please attach Screenshot of the error ?

If you are getting time exceeded error please retry 
Thank you :)

**Comment by dharsan19** [comment]
<img width="1269" alt="Screenshot 2022-11-02 at 3 16 29 PM" src="https://user-images.githubusercontent.com/104762761/199457700-f10c004c-59d2-41b9-aafb-a3a7222bf7c9.png">
You can find the Screenshot of the Error above. The error occur in line 14 return Statement.
Thank You

**Comment by VikashPR** [comment]
![Screenshot 2022-11-02 at 3 39 13 PM](https://user-images.githubusercontent.com/69889418/199458188-4771ece2-7204-4ca0-81db-7b0388a73c8e.png)


> <img alt="Screenshot 2022-11-02 at 3 16 29 PM" width="1269" src="https://user-images.githubusercontent.com/104762761/199457700-f10c004c-59d2-41b9-aafb-a3a7222bf7c9.png">
> 
> You can find the Screenshot of the Error above. The error occur in line 14 return Statement. Thank You

 New C++ code is replaced dharsan, please use c++ code.

**Comment by dharsan19** [comment]
Thank You so much @VikashPR . I'm closing the issue now.

**Comment by VikashPR** [comment]
@dharsan19 please make use of python code for the question attached below

```python
def swap(a,b):
    temp = a
    a = b 
    b = temp 
    return a,b
def partition (a, l, r):
    x = a[r]
    i = (l - 1)
    for j in range(l,r):
        if a[j] <= x:
            i = i + 1
            a[i],a[j] = swap(a[i], a[j])
    a[i + 1],a[r] = swap(a[i + 1],a[r])
    return i + 1
def Quicksort(a, l, r):
    if l < r:
        p = partition(a, l, r)
        print(p)
        for i in range(l,r+1):
            print(a[i],end=' ')
        print()
        Quicksort(a, l, p - 1)
        Quicksort(a, p + 1, r)
n = int(input())
a = list(map(int,input().split()))
Quicksort(a,0,n-1)
```

**Comment by VikashPR** [comment]
Thank you 🙂
