### ISSUE TITLE
Error in Maximum Sum in an Array

### ISSUE THREAD

**Issue by dharsan19** [VikashPR/CCC-Hackerrank#9]
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/104762761/223997392-e17302fa-67a2-40c7-b20c-fbdd60cf1e36.png">

Runtime Error in the program

**Comment by dharsan19** [comment]
Please take a look at this @VikashPR

**Comment by VikashPR** [comment]
@dharsan19 please try again, the code is updated with new java code

**Comment by dharsan19** [comment]
Thank You @VikashPR
